# Generated by Django 5.2.14 on 2026-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extras',
            field=models.JSONField(blank=True, default=list, verbose_name='Servicios adicionales'),
        ),
    ]
