# Generated by Django 5.2.14 on 2026-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_add_booking_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_attendees',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de asistentes'),
        ),
    ]
